FROM debian:bullseye-slim

# openssl と keytool を使えるようにする
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        openjdk-17-jdk-headless \
        openssl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /certs
CMD ["bash"]
