# Maven + JDK17 (Eclipse Temurin)
FROM maven:3.9.6-eclipse-temurin-17

ARG UID
ARG GID
# bashなどの便利コマンド用（必要であれば）
RUN apt-get update && \
#    apt-get install -y vim curl git && \
    groupadd -g $GID devgroup && \
    useradd -m -s /bin/bash -u $UID -g $GID devuser
# --- 作業ディレクトリの準備 ---
# /workspace を作成し、明e示的に所有者を devuser に設定（学習用に明示）
RUN mkdir -p /workspace && chown -R devuser:devgroup /workspace
# ユーザーを切り替え
USER devuser

# 作業ディレクトリを設定
WORKDIR /workspace

CMD ["bash"]