FROM tomcat:9.0

ENV JPDA_ADDRESS=0.0.0.0:8000
ENV JPDA_TRANSPORT=dt_socket

# デフォルトのwebappsの中身を消す
RUN rm -rf /usr/local/tomcat/webapps/*

# WARファイルをデプロイ（名前を ROOT.war にすると直接アクセスできる）
COPY spring-webapp/target/spring-webapp.war /usr/local/tomcat/webapps/ROOT.war

CMD ["catalina.sh", "jpda", "run"]