services:
  builder:
    build:
      context: .   # Dockerfile.dev がある場所（カレントディレクトリ）
      dockerfile: development/Dockerfile.builder
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: spring-builder
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true      # コンテナに対話的に入れる（例: bash）
    tty: true    # 仮想ターミナルを有効化
    command: bash  # ← シェルを起動

    #environment:
      # VS Code Serverのホームディレクトリを/home/devuserに設定
      # これにより、/rootではなく、この非rootユーザーのホームディレクトリにVS Code Serverのファイルが作成されます。
      # - VSCODE_SERVER_CONTAINER_USER_HOME=/home/devuser
  appserver:
    build:
      context: .
      dockerfile: development/Dockerfile.appserver
    container_name: spring-appserver
    expose:
      - "8080"
      - "8000"  # ← デバッグ用ポート
  webserver:
    build:
      context: .
      dockerfile: development/Dockerfile.webserver
    container_name: apache-webserver
    ports:
      - "80:80"
    depends_on:
      - appserver