services:
  builder:
    build:
      context: .   # Dockerfile.dev がある場所（カレントディレクトリ）
      dockerfile: development/Dockerfile.builder
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: spring-builder
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true      # コンテナに対話的に入れる（例: bash）
    tty: true    # 仮想ターミナルを有効化
    command: bash  # ← シェルを起動

    #environment:
      # VS Code Serverのホームディレクトリを/home/devuserに設定
      # これにより、/rootではなく、この非rootユーザーのホームディレクトリにVS Code Serverのファイルが作成されます。
      # - VSCODE_SERVER_CONTAINER_USER_HOME=/home/devuser
  appserver:
    build:
      context: .
      dockerfile: development/Dockerfile.appserver
    container_name: spring-appserver
    ports:
      - "8443:8443"
    expose:
      - "8080"
      #- "8443:8443" # ← HTTPS 用ポート
      - "8000"  # ← デバッグ用ポート
  webserver:
    build:
      context: .
      dockerfile: development/Dockerfile.webserver
    container_name: apache-webserver
    ports:
      - "80:80"
    depends_on:
      - appserver
  db:
    image: postgres:16-alpine  # デフォルトは 16-alpine
    container_name: postgres-db
    restart: unless-stopped # コンテナが停止した場合、再起動する
    env_file:
      - .env                # 下記の変数を読み込む
    environment:            # .env で定義した値をそのまま渡す
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Tokyo # タイムゾーンを設定
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT:-5432}:5432" # 環境変数が設定されていない場合はデフォルトの5432を使用
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"] # データベースが起動しているか確認するコマンド
      interval: 10s # 健康チェックの間隔
      timeout: 5s # 健康チェックのタイムアウト
      retries: 5 # 健康チェックの再試行回数
  certbuilder:
    build:
      context: .
      dockerfile: development/Dockerfile.certbuilder
    container_name: ssl-certbuilder
    user: "${UID}:${GID}"
    volumes:
      - ./build-certs:/certs   # ← 出力先（ホスト共有）
volumes:
  db-data:                             # 永続化用